# Generated by Django 5.2.13 on 2026-04-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер панели (как в книге)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название сцены')),
                ('image', models.ImageField(help_text='Загружайте картинки в формате .webp', upload_to='panels/', verbose_name='Изображение панели (WebP)')),
                ('description', models.TextField(blank=True, verbose_name='Текст / диалоги на панели')),
                ('is_start', models.BooleanField(default=False, verbose_name='Начальная панель')),
                ('is_end', models.BooleanField(default=False, verbose_name='Финальная панель (смерть/победа)')),
            ],
            options={
                'verbose_name': 'Панель комикса',
                'verbose_name_plural': 'Панели комикса',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст выбора действия')),
                ('condition', models.CharField(blank=True, help_text='Например: «нужен нож» или «ОЗ > 50»', max_length=200, verbose_name='Условие (опционально)')),
                ('from_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.panel', verbose_name='От панели')),
                ('to_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_choices', to='game.panel', verbose_name='К панели')),
            ],
            options={
                'verbose_name': 'Вариант выбора',
                'verbose_name_plural': 'Варианты выбора',
            },
        ),
    ]
